### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by NamousNassim** [Deerrorer/dotfiles3#10]
hello great work , i have installed but when i get to the login screen i type my username and password and click login nothing happens

**Comment by 66Bunz** [comment]
@NamousNassim did you find a solution for this, it happened to me too

**Comment by Keyitdev** [comment]
Did you switch session to i3?

**Comment by NamousNassim** [comment]
Exactly i did switch to i3 and it works

**Comment by 66Bunz** [comment]
Yeah, I've got only that session, the login window shows, but once I click login nothing happens

_edit: actually the sessions menu doesn't shows anything_

**Comment by Keyitdev** [comment]
Ok, so you can try this.

1.  In SDDM click `ctrl + alt + f2`.
2.  Login.
3.  Instal `xinit` if you already don't have one.
4.  Create file `~/.xinitrc`.
5.  In `~/.xinitrc` put `exec i3 > /dev/null 2>&1`.
6.  Run `startx`.

(If you don't know how to create files in terminal mode I can help you too, just let me know)

If it works, it means everything is ok. If dosen't it means that WM is not installed or broken.

**Comment by NamousNassim** [comment]
it did work thanks !

**Comment by 66Bunz** [comment]
@Keyitdev this probably works, but I was trying to set it up in a vm, and xorg started to throw some other problems. Thanks for the support anyway.
