### ISSUE TITLE
How to disable login manager (SDDM)

### ISSUE THREAD

**Issue by alphaprads** [Deerrorer/dotfiles3#12]
how do i rewrite password for login screen it doesn't seem to pick up my actual login password i use my computer by logging in other tty3 and then starting the session using startx 

if this requires inputs 
i would love a suggestion with a way to disable the lock screen on startup this would really improve my workflow as i'm using i3 for efficiency

**Comment by Keyitdev** [comment]
It should use your actual password. Maybe change session in sddm (login manager).

**Comment by Keyitdev** [comment]
You can disable the lock screen, just run: ``` sudo systemctl disable sddm.service``` and ``` sudo systemctl stop sddm.service```.

**Comment by alphaprads** [comment]
`sudo systemctl disable sddm.service` worked like a charm.
