### ISSUE TITLE
Should we use pactl instead of amixer commands for i3 config

### ISSUE THREAD

**Issue by rustedusted** [Deerrorer/dotfiles3#19]
Should we use pactl commands to maintain consistency in i3config for managing audio
default i3 config uses pactl, 

as we're using pulseaudio using commands like 

`pactl set-sink-volume @DEFAULT_SINK@ -5%`

seem better as they interact using pulseaudio 

btw the mute command uses pactl as well so it would also be more consistent

I would like to hear your thought not a big change tbh but i want to know why you preferred using amixer over pactl.

**Comment by Keyitdev** [comment]
I prefer amixer to pactl because amixer has a limit at 100% volume. With pactl you can increase volume basically to infinity (which imo is not the best for keybinding).

Run this and see the difference.
```
amixer -D pulse set Master 9999%+
```
```
pactl set-sink-volume @DEFAULT_SINK@ +9999%
```
Perhaps there is a way to limit pactl, but I prefer to simply use amixer.

**Comment by rustedusted** [comment]
oh actually that makes sense 
i didn't even think about that :D 
i actually preferred the pactl for that exact same reason and even forgot that it was the quirk of pactl 

you have really put good thought into this project keep it up man 
also if you ever need any help just ping me

**Comment by rustedusted** [comment]
thanks for the dotfiles :penguin:
