### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by budweisserr** [Deerrorer/dotfiles3#7]
I'm new at arch. Have some troubles with this rice so i want to know how to uninstall completely, because it seems its not working as good as it can. I'm trying to understand some things in installation script and do vice versa but it seems to hard for me. Could u give some info how to completely get rid of all the installed stuff. No hard feelings, rice is good looking btw, just i'm brainless

**Comment by Keyitdev** [comment]
I can help you but firstly, I must obtain more information.
It is a fresh arch installation or you had working configs before (DE/VM)?
What exactly is not working? 
I can show you how to uninstall packages, but some of them are essential for arch (like xorg for example) so it will completely break when you remove them.
