### ISSUE TITLE
Neovim error #2

### ISSUE THREAD

**Issue by haru-vulpes** [Deerrorer/dotfiles3#8]
is normal the luasnip friendly snippet doesnt work on neovim?

**Comment by Keyitdev** [comment]
No i think it should work, let me take a look.

**Comment by Keyitdev** [comment]
```
mv ~/.config/nvim ~/.config/nvim.bak
mv ~/.local/share/nvim ~/.local/share/nvim.bak
git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim
```
This should help, but the color scheme will be broken.
Let me know, if luasnip friendly snippet  works for you.

**Comment by haru-vulpes** [comment]
> ```
> mv ~/.config/nvim ~/.config/nvim.bak
> mv ~/.local/share/nvim ~/.local/share/nvim.bak
> git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
> nvim
> ```
> 
> This should help, but the color scheme will be broken. Let me know, if luasnip friendly snippet works for you.

it works, thx :)
